name: Integration Tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: [ "main", "dev"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  IntegrationTests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/simvue-io/remkit_example:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          uv pip install .
          uv pip install pytest
          uv run pytest tests/integration